create extension if not exists "pgaudit" with schema "extensions";

create extension if not exists "pgroonga" with schema "extensions";

create schema if not exists "next_auth";

create type "public"."feed_privacy" as enum ('public', 'follow', 'private');

create type "public"."feed_status" as enum ('active', 'hide', 'deleted', 'reported');

create type "public"."state" as enum ('like', 'dislike', 'neutral');

create type "public"."type" as enum ('feed', 'comment');

create type "public"."user_privacy" as enum ('owner', 'guest');


  create table "next_auth"."verification_tokens" (
    "identifier" text,
    "token" text not null,
    "expires" timestamp with time zone not null
      );



  create table "public"."comments" (
    "id" uuid not null default gen_random_uuid(),
    "content" text not null,
    "feed_id" uuid not null,
    "parent_id" uuid,
    "created_at" timestamp without time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "user_id" uuid not null
      );



  create table "public"."feed_engagement" (
    "created_at" timestamp with time zone not null default now(),
    "feed_id" uuid not null,
    "user_id" uuid not null,
    "updated_at" timestamp with time zone default now(),
    "id" uuid not null default gen_random_uuid(),
    "state" public.state default 'neutral'::public.state
      );



  create table "public"."feed_images" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "feed_id" uuid not null,
    "image" text not null,
    "updated_at" timestamp with time zone not null default now()
      );



  create table "public"."feed_medias" (
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone default now(),
    "title" text,
    "domain" text,
    "video" text,
    "feed_id" uuid,
    "id" uuid not null default gen_random_uuid()
      );



  create table "public"."feeds" (
    "created_at" timestamp with time zone not null default now(),
    "content" text,
    "updated_at" timestamp with time zone not null default now(),
    "user_id" uuid not null,
    "user_id_public" uuid,
    "privacy" public.feed_privacy not null default 'public'::public.feed_privacy,
    "status" public.feed_status not null default 'active'::public.feed_status,
    "parent_id" uuid,
    "id" uuid not null default gen_random_uuid(),
    "type" public.type not null default 'feed'::public.type,
    "pin" boolean default false
      );



  create table "public"."notifications" (
    "created_at" timestamp with time zone not null default now(),
    "type" text not null,
    "status" boolean not null default false,
    "user_id" uuid,
    "updated_at" timestamp with time zone,
    "feed_id" uuid,
    "comment_id" uuid,
    "id" uuid not null default gen_random_uuid(),
    "user_noti_id" uuid,
    "following_id" uuid,
    "state" public.state,
    "read" boolean default false
      );



  create table "public"."profiles" (
    "id" uuid not null,
    "updated_at" timestamp with time zone,
    "display_name" text,
    "full_name" text,
    "avatar_url" text,
    "website" text,
    "description" text,
    "gender" text not null default 'male'::text,
    "types" text,
    "privacy" public.user_privacy,
    "birthday" date,
    "trial_end" timestamp with time zone,
    "email" text,
    "phonenumber" text
      );



  create table "public"."report" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "content" text
      );



  create table "public"."user_follows" (
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "user_id" uuid not null,
    "following_id" uuid not null
      );


CREATE UNIQUE INDEX token_identifier_unique ON next_auth.verification_tokens USING btree (token, identifier);

CREATE UNIQUE INDEX verification_tokens_pkey ON next_auth.verification_tokens USING btree (token);

CREATE UNIQUE INDEX comments_pkey ON public.comments USING btree (id);

CREATE UNIQUE INDEX feed_images_pkey ON public.feed_images USING btree (id);

CREATE UNIQUE INDEX feed_medias_pkey ON public.feed_medias USING btree (id);

CREATE UNIQUE INDEX feed_reactions_pkey ON public.feed_engagement USING btree (id);

CREATE UNIQUE INDEX feeds_pkey ON public.feeds USING btree (id);

CREATE INDEX ix_name_display_name ON public.profiles USING pgroonga (display_name, full_name);

CREATE UNIQUE INDEX notifications_pkey ON public.notifications USING btree (id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX profiles_username_key ON public.profiles USING btree (full_name);

CREATE UNIQUE INDEX report_pkey ON public.report USING btree (id);

CREATE UNIQUE INDEX unique_feed_engagement ON public.feed_engagement USING btree (user_id, feed_id);

CREATE UNIQUE INDEX user_follows_pkey ON public.user_follows USING btree (user_id, following_id);

alter table "next_auth"."verification_tokens" add constraint "verification_tokens_pkey" PRIMARY KEY using index "verification_tokens_pkey";

alter table "public"."comments" add constraint "comments_pkey" PRIMARY KEY using index "comments_pkey";

alter table "public"."feed_engagement" add constraint "feed_reactions_pkey" PRIMARY KEY using index "feed_reactions_pkey";

alter table "public"."feed_images" add constraint "feed_images_pkey" PRIMARY KEY using index "feed_images_pkey";

alter table "public"."feed_medias" add constraint "feed_medias_pkey" PRIMARY KEY using index "feed_medias_pkey";

alter table "public"."feeds" add constraint "feeds_pkey" PRIMARY KEY using index "feeds_pkey";

alter table "public"."notifications" add constraint "notifications_pkey" PRIMARY KEY using index "notifications_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."report" add constraint "report_pkey" PRIMARY KEY using index "report_pkey";

alter table "public"."user_follows" add constraint "user_follows_pkey" PRIMARY KEY using index "user_follows_pkey";

alter table "next_auth"."verification_tokens" add constraint "token_identifier_unique" UNIQUE using index "token_identifier_unique";

alter table "public"."comments" add constraint "comments_feed_id_fkey" FOREIGN KEY (feed_id) REFERENCES public.feeds(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."comments" validate constraint "comments_feed_id_fkey";

alter table "public"."comments" add constraint "comments_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES public.comments(id) ON DELETE CASCADE not valid;

alter table "public"."comments" validate constraint "comments_parent_id_fkey";

alter table "public"."feed_engagement" add constraint "feed_engagement_feed_id_fkey" FOREIGN KEY (feed_id) REFERENCES public.feeds(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."feed_engagement" validate constraint "feed_engagement_feed_id_fkey";

alter table "public"."feed_engagement" add constraint "feed_engagement_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."feed_engagement" validate constraint "feed_engagement_user_id_fkey";

alter table "public"."feed_engagement" add constraint "unique_feed_engagement" UNIQUE using index "unique_feed_engagement";

alter table "public"."feed_images" add constraint "feed_images_feed_id_fkey" FOREIGN KEY (feed_id) REFERENCES public.feeds(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."feed_images" validate constraint "feed_images_feed_id_fkey";

alter table "public"."feeds" add constraint "feeds_content_check" CHECK ((char_length(content) <= 300)) not valid;

alter table "public"."feeds" validate constraint "feeds_content_check";

alter table "public"."feeds" add constraint "feeds_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES public.feeds(id) ON DELETE CASCADE not valid;

alter table "public"."feeds" validate constraint "feeds_parent_id_fkey";

alter table "public"."feeds" add constraint "feeds_user_id_fkey1" FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."feeds" validate constraint "feeds_user_id_fkey1";

alter table "public"."notifications" add constraint "notifications_comment_id_fkey" FOREIGN KEY (comment_id) REFERENCES public.feeds(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."notifications" validate constraint "notifications_comment_id_fkey";

alter table "public"."notifications" add constraint "notifications_feed_id_fkey" FOREIGN KEY (feed_id) REFERENCES public.feeds(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."notifications" validate constraint "notifications_feed_id_fkey";

alter table "public"."notifications" add constraint "notifications_following_id_fkey" FOREIGN KEY (following_id) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."notifications" validate constraint "notifications_following_id_fkey";

alter table "public"."notifications" add constraint "notifications_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."notifications" validate constraint "notifications_user_id_fkey";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

alter table "public"."profiles" add constraint "profiles_username_key" UNIQUE using index "profiles_username_key";

alter table "public"."profiles" add constraint "username_length" CHECK ((char_length(display_name) >= 3)) not valid;

alter table "public"."profiles" validate constraint "username_length";

alter table "public"."user_follows" add constraint "user_follows_following_id_fkey" FOREIGN KEY (following_id) REFERENCES public.profiles(id) not valid;

alter table "public"."user_follows" validate constraint "user_follows_following_id_fkey";

alter table "public"."user_follows" add constraint "user_follows_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) not valid;

alter table "public"."user_follows" validate constraint "user_follows_user_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION next_auth.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$begin
 insert into next_auth.users (id)
  values (new.id);
  return new;
end;$function$
;

CREATE OR REPLACE FUNCTION next_auth.uid()
 RETURNS uuid
 LANGUAGE sql
 STABLE
AS $function$
  select
    coalesce(
        nullif(current_setting('request.jwt.claim.sub', true), ''),
        (nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'sub')
    )::uuid
$function$
;

CREATE OR REPLACE FUNCTION public.count_descendant_feeds(feed_id uuid)
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
DECLARE
    descendant_count INTEGER;
BEGIN
    WITH RECURSIVE feed_hierarchy AS (
        -- Anchor member: select the parent feed
        SELECT 
            id, 
            parent_id
        FROM 
            public.feeds
        WHERE 
            id = feed_id

        UNION ALL

        -- Recursive member: select children of the previous result set
        SELECT 
            f.id, 
            f.parent_id
        FROM 
            public.feeds f
        INNER JOIN 
            feed_hierarchy fh ON fh.id = f.parent_id
    )
    -- Select count of all feeds in the hierarchy excluding the parent feed
    SELECT COUNT(*)
    INTO descendant_count
    FROM feed_hierarchy
    WHERE id != feed_id;

    RETURN descendant_count;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.find_profiles_and_feeds(search_term text)
 RETURNS SETOF public.profiles
 LANGUAGE plpgsql
AS $function$
DECLARE
    most_followed_ids uuid[];
BEGIN
    SELECT ARRAY(
        SELECT following_id
        FROM (
            SELECT following_id, COUNT(*) as follow_count
            FROM public.user_follows
            GROUP BY following_id
            ORDER BY COUNT(*) DESC
        ) uf
        ) INTO most_followed_ids;

    RETURN QUERY
        SELECT *
        FROM public.profiles
        WHERE id = ANY(array(SELECT unnest(most_followed_ids)))
        AND display_name &@~ search_term
        ORDER BY array_position(most_followed_ids, id);
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_users_with_most_posts(limitdata bigint)
 RETURNS SETOF public.profiles
 LANGUAGE plpgsql
AS $function$
DECLARE
    _profile profiles%ROWTYPE;
BEGIN
    FOR _profile IN
        SELECT profiles.*,  count(feeds.id) AS feed_count
        FROM feeds
        JOIN profiles ON feeds.user_id = profiles.id
        GROUP BY profiles.id  
        ORDER BY feed_count DESC        
        LIMIT  limitData
    LOOP
        RETURN NEXT _profile;
    END LOOP;
    RETURN;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
  BEGIN
    IF new.raw_app_meta_data->>'provider' = 'google' THEN
        INSERT INTO public.profiles (id, display_name, avatar_url, full_name,email)
        VALUES (
            new.id,
            new.raw_user_meta_data->>'full_name', 
            new.raw_user_meta_data->>'avatar_url',
            new.raw_user_meta_data->>'full_name',
            new.email
        );

    ELSIF new.raw_app_meta_data->>'provider' = 'facebook' THEN
        INSERT INTO public.profiles (id, display_name, avatar_url, full_name, email)
        VALUES (
            new.id,
            new.raw_user_meta_data->>'full_name', 
            new.raw_user_meta_data->>'avatar_url',
            new.raw_user_meta_data->>'full_name',
            new.email
        );
        
    ELSE 
        INSERT INTO public.profiles (id, display_name)
        VALUES (
            new.id,
            new.email
        );
    END IF;
    RETURN new;
    END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_notifications()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    owner_id UUID;
    comment_exist UUID;
    follower RECORD;
BEGIN
    IF TG_TABLE_NAME = 'feeds' THEN
        -- Check if the new feed is a comment
        IF NEW.type = 'comment' THEN
            -- Fetch the user_id of the parent feed to notify the owner
            SELECT user_id INTO owner_id
            FROM feeds
            WHERE id = NEW.parent_id;
            
            -- Insert notification for a new comment
            INSERT INTO public.notifications (type, user_id, feed_id, comment_id, user_noti_id)
            VALUES ('comments', NEW.user_id, NEW.parent_id, NEW.id, owner_id);
             ELSIF NEW.type = 'feed' THEN
            -- Check table user_follows where following_id = feed.user_id
            FOR follower IN
                SELECT user_id FROM user_follows WHERE following_id = NEW.user_id
            LOOP
                -- Insert notification per record
                INSERT INTO public.notifications (type, user_id, feed_id, user_noti_id)
                VALUES ('feed', New.user_id, NEW.id, follower.user_id);
            END LOOP;
        END IF;
    ELSIF TG_TABLE_NAME = 'feed_engagement' THEN
            -- Check if the feed is an engagement on another feed (e.g., a like or share)
            SELECT parent_id, user_id INTO comment_exist, owner_id
            FROM feeds
            WHERE id = NEW.feed_id;
            
            IF comment_exist IS NOT NULL THEN
                -- It's a comment engagement
                INSERT INTO public.notifications (type, user_id, feed_id, user_noti_id, state)
                VALUES ('comment_engagement', NEW.user_id, NEW.feed_id, owner_id, NEW.state);
            ELSE
                -- It's a feed engagement
                INSERT INTO public.notifications (type, user_id, feed_id, user_noti_id, state)
                VALUES ('feed_engagement', NEW.user_id, NEW.feed_id, owner_id, NEW.state);
            END IF;
    ELSIF TG_TABLE_NAME = 'user_follows' THEN
        -- Insert notification for a new follower
        INSERT INTO public.notifications (type, user_id, following_id, user_noti_id)
        VALUES ('user_follows', NEW.user_id, NEW.following_id, NEW.following_id);
        
    END IF;
    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.search_default(user_id_in uuid)
 RETURNS SETOF public.profiles
 LANGUAGE plpgsql
AS $function$
DECLARE
    most_followed_ids uuid[];
BEGIN
    IF user_id_in IS NOT NULL THEN
        SELECT ARRAY(
            SELECT following_id
            FROM (
                SELECT following_id, COUNT(*) as follow_count
                FROM public.user_follows
                WHERE following_id <> user_id_in
                GROUP BY following_id
                ORDER BY COUNT(*) DESC
                LIMIT 10
            ) uf
        ) INTO most_followed_ids;
    ELSE
        SELECT ARRAY(
            SELECT following_id
            FROM (
                SELECT following_id, COUNT(*) as follow_count
                FROM public.user_follows
                GROUP BY following_id
                ORDER BY COUNT(*) DESC
                LIMIT 10
            ) uf
        ) INTO most_followed_ids;
    END IF;

    RETURN QUERY
    SELECT *
    FROM public.profiles
    WHERE id = ANY(array(SELECT unnest(most_followed_ids)))
    ORDER BY array_position(most_followed_ids, id);
END;
$function$
;

CREATE OR REPLACE FUNCTION public.verify_user_password(password text, user_id text)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  RETURN EXISTS (
    SELECT id 
    FROM auth.users 
    WHERE id = user_id AND encrypted_password = crypt(password::text, auth.users.encrypted_password)
  );
END;
$function$
;

grant delete on table "next_auth"."verification_tokens" to "service_role";

grant insert on table "next_auth"."verification_tokens" to "service_role";

grant references on table "next_auth"."verification_tokens" to "service_role";

grant select on table "next_auth"."verification_tokens" to "service_role";

grant trigger on table "next_auth"."verification_tokens" to "service_role";

grant truncate on table "next_auth"."verification_tokens" to "service_role";

grant update on table "next_auth"."verification_tokens" to "service_role";

grant delete on table "public"."comments" to "anon";

grant insert on table "public"."comments" to "anon";

grant references on table "public"."comments" to "anon";

grant select on table "public"."comments" to "anon";

grant trigger on table "public"."comments" to "anon";

grant truncate on table "public"."comments" to "anon";

grant update on table "public"."comments" to "anon";

grant delete on table "public"."comments" to "authenticated";

grant insert on table "public"."comments" to "authenticated";

grant references on table "public"."comments" to "authenticated";

grant select on table "public"."comments" to "authenticated";

grant trigger on table "public"."comments" to "authenticated";

grant truncate on table "public"."comments" to "authenticated";

grant update on table "public"."comments" to "authenticated";

grant delete on table "public"."comments" to "service_role";

grant insert on table "public"."comments" to "service_role";

grant references on table "public"."comments" to "service_role";

grant select on table "public"."comments" to "service_role";

grant trigger on table "public"."comments" to "service_role";

grant truncate on table "public"."comments" to "service_role";

grant update on table "public"."comments" to "service_role";

grant delete on table "public"."feed_engagement" to "anon";

grant insert on table "public"."feed_engagement" to "anon";

grant references on table "public"."feed_engagement" to "anon";

grant select on table "public"."feed_engagement" to "anon";

grant trigger on table "public"."feed_engagement" to "anon";

grant truncate on table "public"."feed_engagement" to "anon";

grant update on table "public"."feed_engagement" to "anon";

grant delete on table "public"."feed_engagement" to "authenticated";

grant insert on table "public"."feed_engagement" to "authenticated";

grant references on table "public"."feed_engagement" to "authenticated";

grant select on table "public"."feed_engagement" to "authenticated";

grant trigger on table "public"."feed_engagement" to "authenticated";

grant truncate on table "public"."feed_engagement" to "authenticated";

grant update on table "public"."feed_engagement" to "authenticated";

grant delete on table "public"."feed_engagement" to "service_role";

grant insert on table "public"."feed_engagement" to "service_role";

grant references on table "public"."feed_engagement" to "service_role";

grant select on table "public"."feed_engagement" to "service_role";

grant trigger on table "public"."feed_engagement" to "service_role";

grant truncate on table "public"."feed_engagement" to "service_role";

grant update on table "public"."feed_engagement" to "service_role";

grant delete on table "public"."feed_images" to "anon";

grant insert on table "public"."feed_images" to "anon";

grant references on table "public"."feed_images" to "anon";

grant select on table "public"."feed_images" to "anon";

grant trigger on table "public"."feed_images" to "anon";

grant truncate on table "public"."feed_images" to "anon";

grant update on table "public"."feed_images" to "anon";

grant delete on table "public"."feed_images" to "authenticated";

grant insert on table "public"."feed_images" to "authenticated";

grant references on table "public"."feed_images" to "authenticated";

grant select on table "public"."feed_images" to "authenticated";

grant trigger on table "public"."feed_images" to "authenticated";

grant truncate on table "public"."feed_images" to "authenticated";

grant update on table "public"."feed_images" to "authenticated";

grant delete on table "public"."feed_images" to "service_role";

grant insert on table "public"."feed_images" to "service_role";

grant references on table "public"."feed_images" to "service_role";

grant select on table "public"."feed_images" to "service_role";

grant trigger on table "public"."feed_images" to "service_role";

grant truncate on table "public"."feed_images" to "service_role";

grant update on table "public"."feed_images" to "service_role";

grant delete on table "public"."feed_medias" to "anon";

grant insert on table "public"."feed_medias" to "anon";

grant references on table "public"."feed_medias" to "anon";

grant select on table "public"."feed_medias" to "anon";

grant trigger on table "public"."feed_medias" to "anon";

grant truncate on table "public"."feed_medias" to "anon";

grant update on table "public"."feed_medias" to "anon";

grant delete on table "public"."feed_medias" to "authenticated";

grant insert on table "public"."feed_medias" to "authenticated";

grant references on table "public"."feed_medias" to "authenticated";

grant select on table "public"."feed_medias" to "authenticated";

grant trigger on table "public"."feed_medias" to "authenticated";

grant truncate on table "public"."feed_medias" to "authenticated";

grant update on table "public"."feed_medias" to "authenticated";

grant delete on table "public"."feed_medias" to "service_role";

grant insert on table "public"."feed_medias" to "service_role";

grant references on table "public"."feed_medias" to "service_role";

grant select on table "public"."feed_medias" to "service_role";

grant trigger on table "public"."feed_medias" to "service_role";

grant truncate on table "public"."feed_medias" to "service_role";

grant update on table "public"."feed_medias" to "service_role";

grant delete on table "public"."feeds" to "anon";

grant insert on table "public"."feeds" to "anon";

grant references on table "public"."feeds" to "anon";

grant select on table "public"."feeds" to "anon";

grant trigger on table "public"."feeds" to "anon";

grant truncate on table "public"."feeds" to "anon";

grant update on table "public"."feeds" to "anon";

grant delete on table "public"."feeds" to "authenticated";

grant insert on table "public"."feeds" to "authenticated";

grant references on table "public"."feeds" to "authenticated";

grant select on table "public"."feeds" to "authenticated";

grant trigger on table "public"."feeds" to "authenticated";

grant truncate on table "public"."feeds" to "authenticated";

grant update on table "public"."feeds" to "authenticated";

grant delete on table "public"."feeds" to "service_role";

grant insert on table "public"."feeds" to "service_role";

grant references on table "public"."feeds" to "service_role";

grant select on table "public"."feeds" to "service_role";

grant trigger on table "public"."feeds" to "service_role";

grant truncate on table "public"."feeds" to "service_role";

grant update on table "public"."feeds" to "service_role";

grant delete on table "public"."notifications" to "anon";

grant insert on table "public"."notifications" to "anon";

grant references on table "public"."notifications" to "anon";

grant select on table "public"."notifications" to "anon";

grant trigger on table "public"."notifications" to "anon";

grant truncate on table "public"."notifications" to "anon";

grant update on table "public"."notifications" to "anon";

grant delete on table "public"."notifications" to "authenticated";

grant insert on table "public"."notifications" to "authenticated";

grant references on table "public"."notifications" to "authenticated";

grant select on table "public"."notifications" to "authenticated";

grant trigger on table "public"."notifications" to "authenticated";

grant truncate on table "public"."notifications" to "authenticated";

grant update on table "public"."notifications" to "authenticated";

grant delete on table "public"."notifications" to "service_role";

grant insert on table "public"."notifications" to "service_role";

grant references on table "public"."notifications" to "service_role";

grant select on table "public"."notifications" to "service_role";

grant trigger on table "public"."notifications" to "service_role";

grant truncate on table "public"."notifications" to "service_role";

grant update on table "public"."notifications" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."report" to "anon";

grant insert on table "public"."report" to "anon";

grant references on table "public"."report" to "anon";

grant select on table "public"."report" to "anon";

grant trigger on table "public"."report" to "anon";

grant truncate on table "public"."report" to "anon";

grant update on table "public"."report" to "anon";

grant delete on table "public"."report" to "authenticated";

grant insert on table "public"."report" to "authenticated";

grant references on table "public"."report" to "authenticated";

grant select on table "public"."report" to "authenticated";

grant trigger on table "public"."report" to "authenticated";

grant truncate on table "public"."report" to "authenticated";

grant update on table "public"."report" to "authenticated";

grant delete on table "public"."report" to "service_role";

grant insert on table "public"."report" to "service_role";

grant references on table "public"."report" to "service_role";

grant select on table "public"."report" to "service_role";

grant trigger on table "public"."report" to "service_role";

grant truncate on table "public"."report" to "service_role";

grant update on table "public"."report" to "service_role";

grant delete on table "public"."user_follows" to "anon";

grant insert on table "public"."user_follows" to "anon";

grant references on table "public"."user_follows" to "anon";

grant select on table "public"."user_follows" to "anon";

grant trigger on table "public"."user_follows" to "anon";

grant truncate on table "public"."user_follows" to "anon";

grant update on table "public"."user_follows" to "anon";

grant delete on table "public"."user_follows" to "authenticated";

grant insert on table "public"."user_follows" to "authenticated";

grant references on table "public"."user_follows" to "authenticated";

grant select on table "public"."user_follows" to "authenticated";

grant trigger on table "public"."user_follows" to "authenticated";

grant truncate on table "public"."user_follows" to "authenticated";

grant update on table "public"."user_follows" to "authenticated";

grant delete on table "public"."user_follows" to "service_role";

grant insert on table "public"."user_follows" to "service_role";

grant references on table "public"."user_follows" to "service_role";

grant select on table "public"."user_follows" to "service_role";

grant trigger on table "public"."user_follows" to "service_role";

grant truncate on table "public"."user_follows" to "service_role";

grant update on table "public"."user_follows" to "service_role";

CREATE TRIGGER on_notifications_actions_comments_created AFTER INSERT ON public.comments FOR EACH ROW EXECUTE FUNCTION public.handle_notifications();

CREATE TRIGGER on_notifications_actions_created AFTER INSERT ON public.feed_engagement FOR EACH ROW EXECUTE FUNCTION public.handle_notifications();

CREATE TRIGGER on_notifications_actions_feeds_comments_created AFTER INSERT ON public.feeds FOR EACH ROW EXECUTE FUNCTION public.handle_notifications();

CREATE TRIGGER "push-notifications" AFTER INSERT ON public.notifications FOR EACH ROW EXECUTE FUNCTION supabase_functions.http_request('https://wtuxkawucgrqepemujjf.supabase.co/functions/v1/push-notifications', 'POST', '{"Content-type":"application/json"}', '{}', '1000');

CREATE TRIGGER on_notifications_actions_user_follows_created AFTER INSERT ON public.user_follows FOR EACH ROW EXECUTE FUNCTION public.handle_notifications();

CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


  create policy "avatar 1oj01fe_0"
  on "storage"."objects"
  as permissive
  for update
  to public
using ((bucket_id = 'avatars'::text));



  create policy "avatar 1oj01fe_1"
  on "storage"."objects"
  as permissive
  for delete
  to public
using ((bucket_id = 'avatars'::text));



  create policy "avatar 1oj01fe_2"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check ((bucket_id = 'avatars'::text));



  create policy "avatar 1oj01fe_3"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'avatars'::text));



  create policy "avatars 1oj01fe_0"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'avatars'::text));



  create policy "avatars 1oj01fe_1"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check ((bucket_id = 'avatars'::text));



  create policy "avatars 1oj01fe_2"
  on "storage"."objects"
  as permissive
  for update
  to public
using ((bucket_id = 'avatars'::text));



  create policy "avatars 1oj01fe_3"
  on "storage"."objects"
  as permissive
  for delete
  to public
using ((bucket_id = 'avatars'::text));



  create policy "crud-suzu-storage 23x99_0"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check ((bucket_id = 'suzu'::text));



  create policy "crud-suzu-storage 23x99_1"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'suzu'::text));



  create policy "crud-suzu-storage 23x99_2"
  on "storage"."objects"
  as permissive
  for update
  to public
using ((bucket_id = 'suzu'::text));



  create policy "crud-suzu-storage 23x99_3"
  on "storage"."objects"
  as permissive
  for delete
  to anon, authenticated
using ((bucket_id = 'suzu'::text));



  create policy "suzu-bucket-anon 23x99_0"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'suzu'::text));



